(part "76829-0102"
    (packageRef "768290102")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "181")
    (property "Mouser_Part_Number" "538-76829-0102")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Molex/76829-0102?qs=BZBei1rCqCD7zvLSI%252BZz7Q%3D%3D")
    (property "Manufacturer_Name" "Molex")
    (property "Manufacturer_Part_Number" "76829-0102")
    (property "Description" "Headers & Wire Housings MegaFit Slim Vert Hdr Assy 2 Ckt Tin")
    (property "Datasheet_Link" "https://www.molex.com/pdm_docs/sd/768290102_sd.pdf")
    (property "symbolName1" "76829-0102")
)
